valid:
  email:
    max_length: 255
  name:
    max_length: 100
  phone:
    less_than: 12
    greater_than: 9
  password:
    min_length: 6
  category:
    name:
      max_length: 100
remember: "1"
limit_page:
  users: 10
  news: 3
  top_rates: 4
  top_views: 8
  booking: 10
  tour_search: 5
locale_en: "en"
size_img:
  small: "200x200"
  tour: "400x400"
  home: "262x200"
  news_tour: "850x400"
  tour_booking: "600x400"
